install.packages("ggplot2")
install.packages("gridExtra")
install.packages("grid")
install.packages("gtools")
install.packages('Hmisc')
install.packages('plyr')
install.packages('tidy')
install.packages('multcomp')
install.packages('varhandle')
install.packages('Rmisc')
install.packages('aplpack')
install.packages('tidyverse')
install.packages('ggpubr')
install.packages('rstatix')
install.packages(c("MASS", "akima", "robustbase"))
install.packages(c("akima", "cobs", "robust", "mgcv", "scatterplot3d", "quantreg", "rrcov", "lars", "pwr", "trimcluster", "mc2d", "psych", "Rfit", "DepthProc", "class", "fda", "rankFD"))
install.packages('WRS2')
install.packages('WRS')

